### ISSUE TITLE
Show when was the ticket last updated.

### ISSUE THREAD

**Issue by himani-r5** [IMGIITRoorkee/Ticketify#12]
Currently we can see when was the ticket created , we want to see when was it last updated with changes as well.

**Comment by MadhavDhall** [comment]
May I resolve this issue?

### Suggested Changes
1. Last updated time should be shown below ticket creation time.
2. And there should be mention which time is creation time and which one is updation time.

**Comment by himani-r5** [comment]
Hi,
Yes you can resolve the issue 👍🏼
Implement the suggested changes .

**Comment by MadhavDhall** [comment]
Kindly review the PR linked @himani-r5
