### ISSUE TITLE
Initial landing home screen is blank , fix it by prompting a message to user to create ticket. 

### ISSUE THREAD

**Issue by himani-r5** [IMGIITRoorkee/Ticketify#14]

**Comment by MadhavDhall** [comment]
Please assign me this issue.
### My approach:
I shall add a card with similar style as of ticket which will display, "No tickets yet, Create now" with a button to create a ticket. This will display only when no ticket exists.

**Comment by MadhavDhall** [comment]
Kindly review the PR @himani-r5 mam.

**Comment by MadhavDhall** [comment]
Hi @himani-r5 mam, this issue was resolved 4 days ago but in the leaderboard I have not received points for this issue in the leaderboard. Kindly see to it there may be some problem in the leaderboard code or something manual error or anything else.
Thanks

**Comment by himani-r5** [comment]
Hi
There is some issue with the leaderboard currently , so thats why it isnt
updated . Dont worry , we will fix it soon . You can continue working on
PRs and issues , we will take care of rest :))
