### ISSUE TITLE
Update Date Format to Reflect en-IN Format

### ISSUE THREAD

**Issue by AyushDharDubey** [IMGIITRoorkee/Ticketify#16]
Currently, dates in the application are displayed in the `en-US` format (MM/DD/YYYY). It would be better to:

1. Change the default date format to `en-IN` (DD/MM/YYYY).
2. **Bonus:** Implement functionality to automatically detect the user's locality (e.g., by using services like [ip-api.com](http://ip-api.com/) or similar) and display dates in the appropriate local format.

**Comment by MadhavDhall** [comment]
Kindly assign this issue to me.
### My approach:
By using Intl.DateTimeFormat() :
const localTime = date.toLocaleString('en-US', { timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone });

**Comment by AyushDharDubey** [comment]
ok, the implementation looks great and will help us avoid depending on any third party api.
feel free to go ahead and open a PR.
