### ISSUE TITLE
Add Tooltips to Icons

### ISSUE THREAD

**Issue by rkcoder101** [IMGIITRoorkee/Ticketify#20]
Add tooltips for all icons in the UI wherever necessary

**Comment by disvid** [comment]
Hello @AyushDharDubey @iamgoeldhruv , I want to add tooltips to home and create new ticket icon, can i please work on this ?

**Comment by AyushDharDubey** [comment]
Hi @disvid,

we seriously value your contributions to the project, however, there has been a slight change in protocols. to ensure that all the contributors get sufficient opportunity, now, no contributor may be assigned more than 2 issues at the same time.

please wait until the PRs opened by you are merged or closed, then we will be able to assign the issue to you.
hope you understand


in the meantime, if someone else intends to work on the issue, feel free to let us know below...

**Comment by disvid** [comment]
@AyushDharDubey 
please assign me this one too on merging my 3 open PRs, which are in mergable state right now, thanks

**Comment by AyushDharDubey** [comment]
@disvid the issue has been assigned to you
feel free to open a PR to address this one
