### ISSUE TITLE
Fix Incorrect Placement of Content-Type Header in API Request

### ISSUE THREAD

**Issue by AyushDharDubey** [IMGIITRoorkee/Ticketify#22]
The `Content-Type` header in the `handleSubmit` function of `EditTicketForm.jsx` component is incorrectly placed when making API requests. Specifically, the `"Content-Type": "application/json"` header is incorrectly written outside the `headers` object in the `POST` request

The `Content-Type` header should be correctly placed within the `headers` object for both `PUT` and `POST` requests.

#### **Current Code**
```javascript
const res = await fetch("/api/Tickets", {
  method: "POST",
  body: JSON.stringify({ formData }),
  //@ts-ignore 
  "Content-Type": "application/json",
});
```

#### **Proposed Fix**
```javascript
const res = await fetch("/api/Tickets", {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
  },
  body: JSON.stringify({ formData })
});
```

**Comment by Akshat1276** [comment]
@AyushDharDubey Kindly assign me this issue
Thank you
