### ISSUE TITLE
Incorrect Error Message for Ticket Fetching API

### ISSUE THREAD

**Issue by AyushDharDubey** [IMGIITRoorkee/Ticketify#25]
In the `getTickets` function in `app/page.jsx`, and the `getTicketById` function in `app/TicketPage/[id]/page.jsx`, the `catch` block incorrectly logs the error as `"Error loading topics: "` instead of `"Error loading tickets: "`. Since these functions are responsible for fetching ticket data, this appears to be an inadvertent error, leading to misleading log messages that may confuse developers during debugging.

Wherever "topics" has been mistakenly referred to, it should be rectified to "tickets" to accurately reflect the data being handled in these functions. The error message should clearly reference "tickets" instead of "topics."

**Comment by Akshat1276** [comment]
@AyushDharDubey Kindly assign me this issue.
Thank You
