### ISSUE TITLE
Status is not visible

### ISSUE THREAD

**Issue by iamgoeldhruv** [IMGIITRoorkee/Ticketify#3]
When you will see your tickets on dashboard you will not be able to see status of your ticket.
Add the status option where you can see current status of your  ticket.

**Comment by MadhavDhall** [comment]
May i resolve this issue?
### Suggested changes:

1. Below the progress bar in the ticket card status of the ticket should be displayed below.
2. if the status is completed then there is no need to display the progress bar and Background color of the ticket card should change to some other color.

**Comment by AyushDharDubey** [comment]
Hi @MadhavDhall,
thank you for showing your interest in resolving the issue
your implementation seems good enough
you may go ahead and open a PR to implement the feature.
