### ISSUE TITLE
Add any exciting feature of your own which has a usecase in project

### ISSUE THREAD

**Issue by iamgoeldhruv** [IMGIITRoorkee/Ticketify#48]

**Comment by disvid** [comment]
hi @iamgoeldhruv @AyushDharDubey i want to add a new feature - disclosure widget on categories and status so that it helps organise the home page when a lot of tickets are created.

**Comment by disvid** [comment]
@AyushDharDubey 
apart from this - should i also create a feature for automatically fetching PR template when creating a new PR on github, as it is tedious to copy paste it every time for all contributors

**Comment by AyushDharDubey** [comment]
> @AyushDharDubey apart from this - should i also create a feature for automatically fetching PR template when creating a new PR on github, as it is tedious to copy paste it every time for all contributors
> 
> Ref - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

Yes, of course! I was considering creating a new issue for this as well. now that you've brought it up, feel free to go ahead and create the issue and assign it to yourself.

**Comment by AyushDharDubey** [comment]
> hi @iamgoeldhruv @AyushDharDubey i want to add a new feature - disclosure widget on categories and status so that it helps organise the home page when a lot of tickets are created.
> 
> please assign this issue to me


while i agree that this enhancement would be useful, i feel it may not be a challenging task. if you can come up with a more deserving feature for this **hard** labelled issue, that would be justice for it.

---

if someone else can come up with a more deserving proposal by the time @disvid creates a PR, it would be highly appreciated. in such a situation, @disvid may open a new issue for the work they have done and link a new PR with it. if no one else proposes a more substantial feature in the meantime, @disvid, feel free to open a PR to incorporate the disclosure widget, closing #48.

thank you
